### ISSUE TITLE
Index OutofBound

### ISSUE THREAD

**Issue by dweidai** [lihas/NeuroPy#16]
I am constantly receiving this error running the sample program

Unhandled exception in thread started by <bound method NeuroPy.__packetParser of <NeuroPy.NeuroPy.NeuroPy object at 0x10f3471d0>>
Traceback (most recent call last):
  File "/Users/apple/Desktop/NeuroPy-0.1/NeuroPy/NeuroPy.py", line 106, in __packetParser
    i=i+1; self.attention=int(payload[i],16)
IndexError: list index out of range

Is there any fix to this?

**Comment by dataplayer12** [comment]
@dweidai Did you find a solution to this problem? I am getting the same error.
