### ISSUE TITLE
Clarify this is only for MindWave Mobile

### ISSUE THREAD

**Issue by qubodup** [lihas/NeuroPy#5]
Hello,

I tried using this and only realized after trying to google "rfcomm" since that's your device name that this is for bluetooth devices.

The current NeuroSky products are MindWave, MindSet and MindWave Mobile. The latter ones have Bluetooth, the first one does not.

You might want to point out at the beginning of the readme that this is for MindWave Mobile, since it's easily confused with the MindWave.

Info from http://support.neurosky.com/kb/general-21/what-is-the-difference-between-the-mindset-mindwave-mindwave-mobile-and-xwave

You could point to https://github.com/BarkleyUS/mindwave-python for people who use the original MindWave.

Cheers

**Comment by lihas** [comment]
Updated the README. Thanks for pointing it out. closing the issue.
